def call() {
    dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'OWASP'
    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
}

// additionalArguments: '--scan ./': This specifies that the scan should target the current directory (./). The --scan flag tells Dependency Check which directory to scan for dependencies.
// odcInstallation: 'OWASP': This refers to the OWASP Dependency Check tool installation configured in Jenkins. Jenkins uses this installation to run the scan.
// pattern: '**/dependency-check-report.xml': This specifies the location of the XML report generated by the Dependency Check scan. The pattern **/dependency-check-report.xml indicates that Jenkins should look for this report file in any directory (recursively).